### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by pannet1** [aeron7/aliceblue-python#2]
i am using the same code except for the port, which is 8080 in my case. when the return url is opened after login and 2Fa, i am getting ..
**Unable to connect**
The url construction at the time when it happens is given below
http://127.0.0.1/?code=this_is _ really_big_code&scope=orders&state=not_a_princely_state

i am running MX Linux latest and greatest version

**Comment by aeron7** [comment]
this_is _ really_big_code is access_token
